### ISSUE TITLE
Unintuitive progress/step count with multiple instances

### ISSUE THREAD

**Issue by gtristan** [devcurmudgeon/ybd#138]
When building with multiple instances; each instance shows the current step as the amount of builds that instance has built itself, which does not provide very useful feedback.

Instead, it would be nice if the count was based on how many builds have been run collectively over how many remain to be built; i.e. "completed builds + active builds + 1" would be a good number.

**Comment by devcurmudgeon** [comment]
I've done a first-pass at completed-builds across all instances 653ce9248b4bc05ed35dccbcb4fd1fb8ff28d389.
It may drop a count when more than one instance attempts to update at the same time... i'll sort out a lock at some point
