### ISSUE TITLE
Not rebuild whole module if only 'install-commands' fail

### ISSUE THREAD

**Issue by jjardon** [devcurmudgeon/ybd#194]
Currently, if any of the commands fail, the whole module is built from scratch

**Comment by devcurmudgeon** [comment]
Not going to fix, i think. changing install-commands changes everything, including cache-key.

**Comment by jjardon** [comment]
Can not the artifact resulted from the build step be reused so you dont have to rebuild again in case 'install-commands' step fails?

**Comment by devcurmudgeon** [comment]
i don't see how? install-commands are part of cache-key. you'd have a different artifact.
