### ISSUE TITLE
ybd doesnt respect current schemas

### ISSUE THREAD

**Issue by jjardon** [devcurmudgeon/ybd#195]
I've changed DEFAULTS to add a new build step and ybd seems to ignore it and keep building without errors

looking to the log:

16-03-14 00:00:00 [0/0/0] [DEFINITIONS] WARNING: Unexpected error loading ./schemas/cluster.json-schema
16-03-14 00:00:00 [0/0/0] [DEFINITIONS] WARNING: Unexpected error loading ./schemas/chunk.json-schema
16-03-14 00:00:00 [0/0/0] [DEFINITIONS] WARNING: Unexpected error loading ./schemas/system.json-schema
16-03-14 00:00:00 [0/0/0] [DEFINITIONS] WARNING: Unexpected error loading ./schemas/defaults.json-schema
16-03-14 00:00:00 [0/0/0] [DEFINITIONS] WARNING: Unexpected error loading ./schemas/stratum.json-schema

**Comment by devcurmudgeon** [comment]
I think you mean "ybd doesnt respect current DEFAULTS" rather than schemas? I'll take a look

**Comment by jjardon** [comment]
It respect DEFAULTS, but if the change in DEFAULTS is a change of the current schema (as its when I'm adding a new build step), ybd seems to ignore it

**Comment by devcurmudgeon** [comment]
Should be "fixed" by 646ada1515a216b46ad46a3d6916ac56a337efe8 but this led to a lot of deeper discussion on irc at https://irclogs.baserock.org/%23baserock.2016-03-14.log.html#t2016-03-14T13:44:42

**Comment by devcurmudgeon** [comment]
So unless I'm misunderstanding, there's no magical way to respond to a commit such as https://gitlab.com/jjardon/baserock-definitions/commit/af6151eae706d12c881be7ab28eeb5625ec72814 without separately defining what the whole set is. My 'fix' puts that information into ybd's own fallback defaults.conf, but i'd prefer to see the steps added to DEFAULTS

**Comment by jjardon** [comment]
As a reference, morph fails with this error message:

ERROR: Invalid DEFAULTS file: Additional properties are not allowed ('bootstrap-commands' was unexpected)

**Comment by devcurmudgeon** [comment]
Yes... i still think that the list of *-commands itself should be in DEFAULTS. Every time I suggest it, the discussion heads into deep water, eg this time, about schemas.

**Comment by devcurmudgeon** [comment]
closing this... the ongoing discussion about what should be in DEFAULTS is not a ybd issue
