### ISSUE TITLE
filesystem order can affect what is built

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#21]
So for Kinnison, ybd built erlang for build-system, because...

Kinnison	SotK: Your log: 2015-04-22 08:05:05 [python-markdown] ['strata/core.morph', 'strata/python-cliapp.morph', 'strata/python-wsgi.morph'] | ['strata/erlang.morph', 'strata/django.morph', 'strata/xstatic.morph', 'strata/openstack-clients.morph']

Kinnison	SotK: My log: 2015-04-22 08:09:11 [python-markdown] ['strata/erlang.morph', 'strata/django.morph', 'strata/xstatic.morph', 'strata/openstack-clients.morph'] | ['strata/core.morph', 'strata/python-cliapp.morph', 'strata/python-wsgi.morph']

**Comment by devcurmudgeon** [comment]
worst case, this can try to build something that's not required, and fail. e.g. it attempts systemd on an open-wrt system http://git.baserock.org/cgi-bin/cgit.cgi/baserock/baserock/definitions.git/log/?h=baserock/rdale/openwrt

**Comment by devcurmudgeon** [comment]
this would not be an issue if definitions were unique, but still.

**Comment by richardmaw-codethink** [comment]
You could make it consistent by running dirnames.sort() and filenames.sort() when you use os.walk().

One possible reason for it building the wrong thing may be that definitions has things with the same name, and you start your definition with the one first encountered, but later overwrite its contents with the later one you encounter.

YBD is more vulnerable to this than morph, as it loads every definition in, rather than just those referenced by the definition you specified.

**Comment by devcurmudgeon** [comment]
On 2015-06-09 11:36, richardmaw-codethink wrote:
> You could make it consistent by running dirnames.sort() and
> filenames.sort() when you use os.walk().

great idea. i think it's worth doing that anyway, to make this 
behaviour more deterministic.

> One possible reason for it building the wrong thing may be that
> definitions has things with the same name, and you start your
> definition with the one first encountered, but later overwrite its
> contents with the later one you encounter.

yup.

> YBD is more vulnerable to this than morph, as it loads every
> definition in, rather than just those referenced by the definition 
> you
> specified.

yes. i thought i'd addressed this already, but definitions.py is still 
crazily complex at the moment and clearly i was wrong.

Thanks for the feedback!

**Comment by devcurmudgeon** [comment]
I'm closing this, based on @perryl's fix.
