### ISSUE TITLE
Fails to build qt5/qtquick1

### ISSUE THREAD

**Issue by perryl** [devcurmudgeon/ybd#214]
Ran into this issue building genivi-demo-platform-x86_32-generic.morph on a linux32 baserock chroot:

16-04-27 01:32:42 [319/360/360] [qtquick1] Try downloading qtquick1.8125817ee4be29018d82355208743cd1317590fe0da2ddb1ae6fdcdb5700b9e7
16-04-27 01:32:51 [319/360/360] [qtquick1] Starting build of qtquick1.8125817ee4be29018d82355208743cd1317590fe0da2ddb1ae6fdcdb5700b9e7 
16-04-27 01:32:51 [319/360/360] [qtquick1] Try fetching tarball git___git_baserock_org_delta_qt5_qtquick1.tar 
--2016-04-27 17:25:03--  http://git.baserock.org/tarballs/git___git_baserock_org_delta_qt5_qtquick1.tar
Resolving git.baserock.org... 185.43.218.183
Connecting to git.baserock.org|185.43.218.183|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28108288 (27M) [application/octet-stream]
Saving to: 'git___git_baserock_org_delta_qt5_qtquick1.tar'

git___git_baserock_org_delta_q 100%[======================================================>]  26.81M  5.97MB/s   in 4.5s   

2016-04-27 17:25:07 (5.93 MB/s) - 'git___git_baserock_org_delta_qt5_qtquick1.tar' saved [28108288/28108288]

16-04-27 01:32:55 [319/360/360] [qtquick1] Refreshing mirror for upstream:qt5/qtquick1 
16-04-27 01:32:56 [319/360/360] [qtquick1] Git repo is mirrored at /src/gits/git___git_baserock_org_delta_qt5_qtquick1
16-04-27 01:32:56 [319/360/360] [qtquick1] Git checkout upstream:qt5/qtquick1 in /src/tmp/tmpfFeote/qtquick1.build 
16-04-27 01:32:56 [319/360/360] [qtquick1] Upstream version 1f92491b v5.4.0 (v5.4.0 + 0 commits) 
16-04-27 01:32:56 [319/360/360] [qtquick1] Checking git submodules 
16-04-27 01:32:56 [319/360/360] [qtquick1] ERROR: a surprise exception happened 
Traceback (most recent call last):
  File "/src/ybd/ybd/sandbox.py", line 60, in setup
    yield
  File "/src/ybd/ybd/assembly.py", line 64, in compose
    build(defs, component)     # bring in 'build-depends', and run make
  File "/src/ybd/ybd/assembly.py", line 91, in build
    run_build(defs, component)
  File "/src/ybd/ybd/assembly.py", line 112, in run_build
    repos.checkout(this)
  File "/src/ybd/ybd/repos.py", line 173, in checkout
    checkout_submodules(this)
  File "/src/ybd/ybd/repos.py", line 239, in checkout_submodules
    with open('.gitmodules', "r") as gitfile:
IOError: [Errno 2] No such file or directory: '.gitmodules'

16-04-27 01:32:56 [319/360/360] [qtquick1] ERROR: sandbox debris is at /src/tmp/tmpfFeote

**Comment by devcurmudgeon** [comment]
i can't see any definition for qtquick1 in master...?

**Comment by jjardon** [comment]
This was a error in definitions; a module (qtquick) had submodule instructions but the repo doesn't actually have any submodule
