### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 230: ordinal not in range(128)

### ISSUE THREAD

**Issue by jjardon** [devcurmudgeon/ybd#218]
Using ybd commit 6aa0ffb21feaccbd5cd6de5168a1e8a2eadbc691 , Im getting this error when trying to build a system:

0 16-05-11 00:00:04 [0/169/402] [SETUP] 18GB is enough free space 
0 16-05-11 00:00:05 [0/169/402] [systems/ivi-system-x86_32.morph] Sandbox using <module 'sandboxlib.linux_user_chroot' from '/usr/lib/python2.7/site-packages/sandboxlib/linux_user_chroot.pyc'> 
0 16-05-11 00:00:05 [0/169/402] [ivi-system-x86_32] Installing audio-bluetooth splits ['audio-bluetooth-minimal', 'audio-bluetooth-runtime']
0 16-05-11 00:00:05 [0/169/402] [ivi-system-x86_32] Installing bsp-x86_32-generic splits ['bsp-x86_32-generic-minimal', 'bsp-x86_32-generic-runtime']
0 16-05-11 00:00:06 [0/169/402] [ivi-system-x86_32] Installing build-essential splits ['build-essential-minimal', 'build-essential-runtime']
0 16-05-11 00:00:08 [0/169/402] [ivi-system-x86_32] Installing core splits ['core-minimal', 'core-runtime']
Traceback (most recent call last):
  File "/src/ybd/ybd/splitting.py", line 100, in install_split_artifacts
    utils.copy_file_list(path, component['sandbox'], filelist)
  File "/src/ybd/ybd/utils.py", line 148, in copy_file_list
    _process_list(srcpath, destpath, filelist, _copyfun)
  File "/src/ybd/ybd/utils.py", line 192, in _process_list
    file_stat = os.lstat(srcpath)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 230: ordinal not in range(128)
0 16-05-11 00:00:14 [0/169/402] [core] ERROR: failed copying files from /root/ybd/artifacts/ca-certificates.1451b9b7e6feede620fadb33d0d2ab69ec8b5fe5c7006e22feda14c637d5275e/ca-certificates.1451b9b7e6feede620fadb33d0d2ab69ec8b5fe5c7006e22feda14c637d5275e.unpacked/baserock/ca-certificates.meta

**Comment by jjardon** [comment]
This is a problem in the configuration of the locales (UTF8) in my baserock chroot; I will send a patch to baserock to fix this

**Comment by devcurmudgeon** [comment]
After discussion on irc, this appears to be a problem with locales in baserock definitions. My fix allows the ci builds to complete, but it's "sweeping the problem under the carpet"

**Comment by jjardon** [comment]
Seems this was not a problem in locales in my baserock chroot, its failing to build in the ci system as well:

https://gitlab.com/baserock/definitions/builds/2168068#down-build-trace

**Comment by devcurmudgeon** [comment]
Fixed by lemming's d6cd8f0f2425d633dc0182e0b7ad63538bacba5f
