### ISSUE TITLE
kbas chokes on artifacts with an @ in the name

### ISSUE THREAD

**Issue by locallycompact** [devcurmudgeon/ybd#226]
Possibly it isn't safe to allow definitions to do this, but anyway kbas doesn't like it.

    16-06-21 00:03:11 [1/8/443] [gstreamer@0.10] Elapsed time for build of gstreamer@0.10.5d2ea8b051ebcda2a3d73f97bec82f48c60354b246081139c6efb9aece3f8ad4 00:01:41
    16-06-21 00:03:11 [1/8/443] [gstreamer@0.10] Starting artifact creation 
    16-06-21 00:03:11 [1/8/443] [gstreamer@0.10] Splitting None
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Cached 4798068 bytes b8369291bef60760858415e34f657567 as gstreamer@0.10.5d2ea8b051ebcda2a3d73f97bec82f48c60354b246081139c6efb9aece3f8ad4
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Starting upload 
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Artifact server problem: 400
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Failed to upload gstreamer@0.10.5d2ea8b051ebcda2a3d73f97bec82f48c60354b246081139c6efb9aece3f8ad4
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Elapsed time for upload 00:00:00
    16-06-21 00:03:17 [2/8/443] [gstreamer@0.10] Elapsed time for artifact creation 00:00:05

**Comment by devcurmudgeon** [comment]
After a lot of faffing, this is properly fixed in ac41d64
