### ISSUE TITLE
ybd returns success on failure

### ISSUE THREAD

**Issue by richardipsum** [devcurmudgeon/ybd#34]
There are a number of places where we call subprocess.call() without checking the result,
it's probably better to use subprocess.check_call here, catching exceptions where necessary.

Unsurprisingly we partially reimplement parts of morph for handling gitdirs and repo caching,
since that part of morph is actually pretty good, I think we could make life easier for ourselves
by reusing that code.

**Comment by richardipsum** [comment]
Should probably include an example of this problem,

     2015-05-21 07:22:36 [stage1-binutils] Fetching from upstream to resolve   b1d3b01332ae49a60ff5d6bf53d3a5b1805769c8 
    fatal: Not a git repository (or any parent up to mount point /src)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


    2015-05-21 07:22:36 [stage1-binutils] ERROR: could not find tree for ref  b1d3b01332ae49a60ff5d6bf53d3a5b1805769c8

    2015-05-21 07:22:36 [TOTAL] Elapsed time 00:00:03
    % echo $?
    0

**Comment by devcurmudgeon** [comment]
> Unsurprisingly we partially reimplement parts of morph for handling gitdirs and repo caching,
since that part of morph is actually pretty good, I think we could make life easier for ourselves
by reusing that code.

iirc, i already did re-use morph's code for this, but tried to 'improve' it. maybe i've made it worse...

**Comment by devcurmudgeon** [comment]
I fixed the titled problem at aad862714fc20ba6e5230a8ca0774886732a4782 but there's still the question of tidying up how we do the subprocess calls, i think. anyway, closing this for now.
