### ISSUE TITLE
x86_32 build fails at glibc

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#38]
see http://paste.baserock.org/apalarukak

**Comment by palvarez89** [comment]
Is this trying to build a x86_32 system in a x86_64 environment?

**Comment by devcurmudgeon** [comment]
On 2015-06-01 17:21, Pedro Alvarez Piedehierro wrote:
> Is this trying to build a x86_32 system in a x86_64 environment?

Yes. I thought that historically morph could do that, but now notice it 
refuses saying 'are you trying to cross-build'

**Comment by palvarez89** [comment]
Ok, I was just wondering because I don't know if it's possible. Would be good to test this in a x86_32 system to see if it also fails.

**Comment by devcurmudgeon** [comment]
closed until cross-build is made to work...
