### ISSUE TITLE
devel-system triggers recursion error

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#8]
2015-03-30 10:34:14 [procps-ng] Cache_key is procps-ng@74a54a9b90dae1d8c1d6e1c4d31bc2c4d42a5fc236ead5ce0eba72b053cc73ab
2015-03-30 10:34:14 [CACHE-KEYS] Elapsed time 00:00:01
2015-03-30 10:34:14 [TOTAL] Elapsed time 00:00:02
2015-03-30 10:34:14 [devel-system-x86_64-generic] Finished 
Traceback (most recent call last):
  File "/src/ybd/ybd.py", line 37, in <module>
    cache.get_cache(target)
  File "/src/ybd/cache.py", line 95, in get_cache
    cache_key(this) + '.tar.gz')
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[component['name']] = cache_key(component)
  File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[component['name']] = cache_key(component)
...

 File "/src/ybd/cache.py", line 53, in cache_key
    hash_factors[component['name']] = cache_key(component)
  File "/src/ybd/cache.py", line 34, in cache_key
    defs = definitions.Definitions()
  File "/src/ybd/definitions.py", line 33, in __init__
    if self.__definitions != {}:
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by devcurmudgeon** [comment]
'ipmitool' occurs both in 'tools' and 'cxmanage'.

**Comment by devcurmudgeon** [comment]
the following are all defined as both strata and chunks:
- ruby
- swift
- lorry
- ansible

**Comment by grahamfinney** [comment]
Debug show cycling between ruby-1.8, libyaml and ruby.

'ruby' is down as a dependency and should be treated as a chunk, appears to be treated as a stratum and so is recursively being processed as a stratum instead of as a chunk.

Go into cache_key with definition 'ruby'.
We recurse with definition ruby-1.8, which calls cache_key which returns definition['cache']

We recurse with definition libyaml,  which calls cache_key which returns definition.get('repo'), then definition['cache']

For ruby:
  goes into cache_key, 
  definition.get('cache') returns nothing, 
  definition.get('repo')  returns 'upstream:ruby'
  definition.get('tree')  returns '098594f0c7a2dcff3e448eabc60a7d05db859c49'

Hence (definition.get('repo') and not definition.get('tree')) is false, so we just continue, get the contents of definition, and the cycle continues.

I don't understand the reason for the logic: 

    if definition.get('repo') and not definition.get('tree'):
        definition['tree'] = repos.get_tree(definition)

**Comment by devcurmudgeon** [comment]
if definition.get('repo'): means this is a chunk with code in git
if not definition.get('tree'): means we don't know the tree for the git commit  yet.
so we look it up (using a git command) in repos.get_tree - but that function may find itself needing to clone the repo first.

the actual problem is that ruby is both a stratum and a chunk. i'm working to solve it, but it's proving surprisingly tricky.

ideally i'd like upstream to make definition names unique, but ultimately i'd like ybd to build all previous versions of definitions.git and morphs.git so there has to be a code fix.

**Comment by grahamfinney** [comment]
I also came to the conclusion that ruby's being both was a problem, but I thought there was something else I didn't grasp around that bit of code.

**Comment by grahamfinney** [comment]
I'm thinking, could definitions.get() be used with another parameter to qualify its search, to make it look for something that is of a particular type (like 'chunk' rather than 'stratum')? This gets it away from the 'contents' generic idea, but still...

**Comment by devcurmudgeon** [comment]
That would work, but defeats the objective of proving that definitions can be generic. 

In the short term, baserockers appear to have agreed to make definition names unique, so I'll submit a patch upstream for that. This bug will stay open, though, because Ideally I want ybd to build old definitions examples and morphs.git examples too.

**Comment by devcurmudgeon** [comment]
Fixed... f68586b2183eb1ff95bfeab47c6cc3df35c6884d switches the lookup of definitions to work on path instead of name.

There may be a simpler solution, but I couldn't find it

**Comment by grahamfinney** [comment]
I'm fine with this, buy I think you misunderstood me. Externally, defs would still be generic, but within YBD, internally, a param could have been used to tell defs.get() to look for a stratum or a chunk. Just an idea.

**Comment by devcurmudgeon** [comment]
Maybe I did - this is quite complicated as you know :). 

So far I've been aiming to prove that YBD can ignore the kind field altogether, because ultimately I want definitions to be nestable.
